version: '3.8'
services:
  preprocessing-service:
    build: ./preprocessing_service
    ports:
      - "5000:5000"
    depends_on:
      - prediction-service

  prediction-service:
    build: ./prediction_service
    expose:
      - "5001"